import { describe, expect, it } from 'vitest'
import { generateHeader } from './main.js'

describe('gen-msgs', () => {
  it('includes a #pragma once and namespace m5proto::kind', () => {
    const out = generateHeader()
    expect(out).toContain('#pragma once')
    expect(out).toContain('namespace m5proto')
    expect(out).toContain('namespace kind')
  })

  it('emits all host and device kinds as constexpr const char*', () => {
    const out = generateHeader()
    expect(out).toContain('constexpr const char* hello = "hello";')
    expect(out).toContain('constexpr const char* hello_ack = "hello.ack";')
    expect(out).toContain('constexpr const char* status = "status";')
    expect(out).toContain('constexpr const char* device_event = "device.event";')
  })

  it('emits state and urgency constants', () => {
    const out = generateHeader()
    expect(out).toContain('namespace state')
    expect(out).toContain('constexpr const char* active = "active";')
    expect(out).toContain('constexpr const char* idle = "idle";')
    expect(out).toContain('namespace urgency')
    expect(out).toContain('constexpr const char* high = "high";')
  })

  it('starts with a generation banner referencing the source', () => {
    const out = generateHeader()
    expect(out).toMatch(/Generated by tools\/gen-msgs/)
    expect(out).toMatch(/DO NOT EDIT/)
  })
})
