#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { DEVICE_KINDS, HOST_KINDS, STATES, URGENCY } from '@m5stack-coding-toys/protocol'

// Use lowercase snake_case to avoid colliding with Arduino macros like
// HIGH, LOW, ERROR, INPUT, OUTPUT that pollute the preprocessor.
const IDENT = (s: string): string => s.toLowerCase().replace(/[.\-]/g, '_')

function emitNamespace(ns: string, values: readonly string[]): string {
  const lines = values.map((v) => `    constexpr const char* ${IDENT(v)} = "${v}";`)
  return `  namespace ${ns} {\n${lines.join('\n')}\n  }`
}

export function generateHeader(): string {
  const hostLines = HOST_KINDS.map((k) => `    constexpr const char* ${IDENT(k)} = "${k}";`).join(
    '\n',
  )
  const deviceLines = DEVICE_KINDS.map(
    (k) => `    constexpr const char* ${IDENT(k)} = "${k}";`,
  ).join('\n')
  return `// Generated by tools/gen-msgs from @m5stack-coding-toys/protocol.
// DO NOT EDIT — re-run \`pnpm gen:msgs\`.

#pragma once

namespace m5proto {

  namespace kind {
    // host -> device
${hostLines}

    // device -> host
${deviceLines}
  }

${emitNamespace('state', STATES)}

${emitNamespace('urgency', URGENCY)}

}  // namespace m5proto
`
}

function main(): number {
  const here = dirname(fileURLToPath(import.meta.url))
  const outPath = resolve(here, '../../../firmware/lib/m5proto/messages.h')
  const content = generateHeader()
  const check = process.argv.includes('--check')
  if (check) {
    let existing: string
    try {
      existing = readFileSync(outPath, 'utf8')
    } catch {
      console.error(`[gen-msgs --check] ${outPath} does not exist`)
      return 1
    }
    if (existing !== content) {
      console.error(`[gen-msgs --check] ${outPath} is stale; re-run gen-msgs`)
      return 1
    }
    console.log(`[gen-msgs --check] ${outPath} is up to date`)
    return 0
  }
  writeFileSync(outPath, content)
  console.log(`[gen-msgs] wrote ${outPath}`)
  return 0
}

if (import.meta.url === `file://${process.argv[1]}`) {
  process.exit(main())
}
