// Generated by tools/gen-msgs from @m5stack-coding-toys/protocol.
// DO NOT EDIT — re-run `pnpm gen:msgs`.

#pragma once

namespace m5proto {

  namespace kind {
    // host -> device
    constexpr const char* hello = "hello";
    constexpr const char* status = "status";
    constexpr const char* notify = "notify";
    constexpr const char* ping = "ping";
    constexpr const char* screenshot = "screenshot";
    constexpr const char* tap = "tap";

    // device -> host
    constexpr const char* hello_ack = "hello.ack";
    constexpr const char* notify_ack = "notify.ack";
    constexpr const char* device_event = "device.event";
    constexpr const char* pong = "pong";
    constexpr const char* screenshot_ack = "screenshot.ack";
    constexpr const char* tap_ack = "tap.ack";
  }

  namespace state {
    constexpr const char* active = "active";
    constexpr const char* idle = "idle";
  }

  namespace urgency {
    constexpr const char* low = "low";
    constexpr const char* normal = "normal";
    constexpr const char* high = "high";
  }

}  // namespace m5proto
